"""add unique constraint in v0 and v1

Revision ID: 15ffffcd8f0b
Revises: 80e6a24e3643
Create Date: 2021-10-22 08:44:29.080810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ffffcd8f0b'
down_revision = '80e6a24e3643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_v0_v1_uc', 'casbin_rule', ['v0', 'v1'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_v0_v1_uc', 'casbin_rule', type_='unique')
    # ### end Alembic commands ###
